// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szetvocatauhbyrdilec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6ZXR2b2NhdGF1aGJ5cmRpbGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzI1NDMsImV4cCI6MjA2OTEwODU0M30.t99obbZkgWqzpiV0omcSxc2uQYPpwxZLFEJ2mLcJJiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});